In [1]:
%load_ext autoreload
%autoreload 2

import numpy as np
import gym

import gym_gridworld
import dynamic_programming

In [29]:
def print_policy(policy, terminal_states):
    arrows = {0: '\u2191', 1:'\u2192' , 2:'\u2193' , 3:'\u2190'}
    terminal_state = '\u25A0'
    n = int(np.sqrt(len(policy)))
    for i in range(n):
        string = ""
        for j in range(n):
            ij = i*n + j
            if ij in terminal_states:
                string += terminal_state
            else:
                string += arrows[policy[ij]]
        print(string)


def clean_print(V, PI, k, terminal_states):
    if int == type(k):
        print("Policy found in {} iterations".format(k))
    else:
        print("Policy found in {} iterations, where each policy evaluation lasted for k = {}".format(len(k), k))
    n = np.sqrt(len(V)).astype(int)
    print("\nV\n", np.array(V).round(1).reshape((n,n)))
    print("\nPI")
    print_policy(PI, terminal_states)
    
def compute_algorithm(algorithm, algorithm_name, env, dicount_factor, modified_max_k=np.Inf):
    if modified_max_k != np.Inf:
        V, PI, k = algorithm(env, dicount_factor, modified_max_k = modified_max_k)
    else:
        V, PI, k = algorithm(env, dicount_factor)
    print("\n\n"+algorithm_name)
    clean_print(V, PI, k, grid_world.terminal_states)



env = gym.make("gridworld-v0", n=5, p_action_works=0.75)
dicount_factor = 0.9

compute_algorithm(dynamic_programming.policy_iteration, "POLICY ITERATION", env, dicount_factor)
# compute_algorithm(dynamic_programming.policy_iteration, "MODIFIED POLICY ITERATION", env, dicount_factor, modified_max_k=2)
# compute_algorithm(dynamic_programming.value_iteration, "VALUE ITERATION", env, dicount_factor)



POLICY ITERATION
Policy found in 4 iterations, where each policy evaluation lasted for k = [64, 17, 14, 7]

V
 [[0.  6.9 8.3 9.6 0. ]
 [5.3 6.3 7.3 8.4 9.6]
 [4.9 5.6 6.4 7.3 8.3]
 [4.3 4.9 5.6 6.4 7.2]
 [3.9 4.4 4.9 5.6 6.3]]

PI
■→→→■
→→→→↑
→→→↑↑
↑→↑↑↑
→→→↑↑
