In [2]:
%load_ext autoreload
%autoreload 2

import numpy as np
import gym

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [3]:
env = gym.make('Pendulum-v0')

observation = env.reset()
for t in range(10):
    env.render()
    print(observation)
    action = env.action_space.sample()
    observation, reward, done, info = env.step(action)
    if done:
        print("Episode finished after {} timesteps".format(t+1))
        break
env.close()

[-0.70363408  0.71056251 -0.21267402]
[-0.72312512  0.69071706  0.55634259]
[-0.76560731  0.6433082   1.27337431]
[-0.81962511  0.57290023  1.77542999]
[-0.87337028  0.48705683  2.02646618]
[-0.92892833  0.37025959  2.58856439]
[-0.97448323  0.22446033  3.05798504]
[-0.99860059  0.05288545  3.46958139]
[-0.99415334 -0.10797744  3.2219699 ]
[-0.96559741 -0.26004163  3.09753894]


In [7]:
np.arccos(-1)

3.141592653589793