In [2]:
%load_ext autoreload
%autoreload 2

import numpy as np
import gym

In [3]:
env = gym.make('Pendulum-v0')

observation = env.reset()
for t in range(10):
    env.render()
    print(observation)
    action = env.action_space.sample()
    observation, reward, done, info = env.step(action)
    if done:
        print("Episode finished after {} timesteps".format(t+1))
        break
env.close()

[ 0.99953841 -0.03038034  0.95853855]
[0.99991243 0.01323401 0.8723882 ]
[0.99901667 0.0443362  0.62232687]
[0.99651498 0.08341395 0.783205  ]
[0.99079291 0.13538617 1.04584437]
[0.98100154 0.19399993 1.18869396]
[0.96335852 0.26821699 1.52607649]
[0.93365034 0.35818577 1.89564552]
[0.88542491 0.46478245 2.34129779]
[0.8192901  0.57337923 2.54471232]
